# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet-ALL-2Phase-384-midRes
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: ALL
    type: PairedImageDataset
    dataroot_gt: /mnt/lustre/GPU7/home/yangbo/workspace/data/LSDIR/gt_all.lmdb
    dataroot_lq: /mnt/lustre/GPU7/home/yangbo/workspace/data/LSDIR/noise.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 384
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: /mnt/lustre/GPU7/home/yangbo/workspace/data/Denoising/val/gt.lmdb
    dataroot_lq: /mnt/lustre/GPU7/home/yangbo/workspace/data/Denoising/val/noise.lmdb
    io_backend:
      type: lmdb


network_g:
  type: RTAFNetLocal
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 16
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ./team14_RTAFNet.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
